### ISSUE TITLE
Any detail writeups for the source code?

### ISSUE THREAD

**Issue by joydo** [chrisps/Hexext#3]
Recently, I am attempting to restore the ollvm-based(obfuscator framework) codebase. I want to use the ida microcode api for solving it . But I only have ida 7.0. So @chrisps, can you give me some more detailed writeups?  This way, I can  eliminate some unnecessary jumps and optimize for the decompiling result !

**Comment by chrisps** [comment]
Provide some screenshots of the code you need to implement optimization rules for and I can give you an overview of what you will need to use to implement them

**Comment by joydo** [comment]
Ok,The following snapshots are my puzzles.

**First Section is about the control flow flattening:**

**IDA decompiling result:**
![image](https://user-images.githubusercontent.com/12075969/64058022-743be400-cbd7-11e9-81c5-b43a016e1025.png)
![image](https://user-images.githubusercontent.com/12075969/64058055-df85b600-cbd7-11e9-87e2-dbe6c992a948.png)

**The corresponding assembly code:**
![image](https://user-images.githubusercontent.com/12075969/64058034-8e75c200-cbd7-11e9-885e-5237a47d3def.png)

**Second Section is for the Opaque Predicates:**

**IDA decompiling code:**
![image](https://user-images.githubusercontent.com/12075969/64058041-a51c1900-cbd7-11e9-9d4e-ee8886433f4a.png)
![image](https://user-images.githubusercontent.com/12075969/64058042-b06f4480-cbd7-11e9-8682-2386672e741a.png)


**The corresponding assembly code:**
![image](https://user-images.githubusercontent.com/12075969/64058047-ce3ca980-cbd7-11e9-804b-f4b303028fa9.png)


The First section has many useless jumps(these jumps need to compare one conditional variable), I need to use microcode-related api to optimize out these  jumps.

The second section is easy to repair, I need to use the pattern matching method for replacing the calculation result. 

At first,I want to use the symbol execution to solve these problem,but I will have to modify some instructions. Also, I cannot use the ida decompiler plugin. Then , I was inspired by the github repo [Hexrays Deobfuscation(microcode api)](https://github.com/RolfRolles/HexRaysDeob). So I want to adjust his method for my situation. But ida 7.0 don't have enough microcode api. 

So I refer to your microcode implementation. But some place have no enough annotation. could you give me some idea? Thanks.

**Comment by chrisps** [comment]
For both parts you're going to have the modify hexext. See the files in the combine_rules/ subdirectory for reference. you need to implement custom combine rules. See the late_flag ops rules for examples of modifying control flow. Jmp destinations are represented as eas before local optimization, and basic block numbers afterwards, so be aware of that when writing a rule that modifies control flow. 

For information on what each microinstruction takes for operands, look at the actual hexrays sdk. The operand types they take are the same in 7.0. To simplify the task you should make your control flow changes after local optimization, otherwise you will have to deal with m_jcnd instructions instead of m_jbe, m_jnz, etc.

**Comment by joydo** [comment]
As for the local optimization, First I have to write one related custom rule that modifies related control flow , The I need to use the "hexext::install_locopt_cb(...)" install my custom callback function, Right?

**Comment by chrisps** [comment]
You want your callback to repeatedly run during optimization, so you're going to want to implement it as a combine rule. Local optimization callback is not the way to go. In your COMB_RULE_IMPLEMENT body, call hexext::has_locopt_run() and return 0 if it returns false. Check the bottom of the main combine rules file to see how combine rules are added as callbacks. Uncomment the disabled line in plugin main that installs the dump_mba callback to see the functions microcode to help implement your rules. Then look at the rules in cleanup_late_flag_ops to see how i do my control flow modifications and build off of that. You'll see I have a lot of helper functions for extracting operands for rules. Use those and it'll make your life much easier. Start simple with the opaque predicates, those rules can run at any stage and will give you much cleaner output once theyre implemented. If you need more  information feel free to email me, my gmail is on my github profile. If you encounter interrs you should reference the numbers against the leaked 7.2 sdk's verifier/verify.cpp header file. Theres a lot of things i do in hexext that i dont have comments for explaining why theyre done, you will likely need more guidance.

**Comment by joydo** [comment]
Thanks for your pleasant reply.
